version: '3.7'
services:
  app:
    build: .
    container_name: validator-ejector
    restart: unless-stopped
    environment:
      - EXECUTION_NODE=${EXECUTION_NODE}
      - CONSENSUS_NODE=${CONSENSUS_NODE}
      - LOCATOR_ADDRESS=${LOCATOR_ADDRESS}
      - MESSAGES_LOCATION=${MESSAGES_LOCATION}
      - MESSAGES_PASSWORD=${MESSAGES_PASSWORD}
      - BLOCKS_PRELOAD=${BLOCKS_PRELOAD}
      - HTTP_PORT=${HTTP_PORT}
      - RUN_METRICS=${RUN_METRICS}
      - RUN_HEALTH_CHECK=${RUN_HEALTH_CHECK}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FORMAT=${LOGGER_FORMAT}
      - LOGGER_SECRETS=${LOGGER_SECRETS}
      - DRY_RUN=${DRY_RUN}
      - IGNORE_FIRST_CERTIFICATION=${IGNORE_FIRST_CERTIFICATION}
      - VALIDATOR_WEBHOOK_NODE=${VALIDATOR_WEBHOOK_NODE}
      - VALIDATOR_WEBHOOK_AUTH=${VALIDATOR_WEBHOOK_AUTH}
      - VALIDATOR_WEBHOOK_GET=${VALIDATOR_WEBHOOK_GET}
      - VALIDATOR_WEBHOOK_SEND=${VALIDATOR_WEBHOOK_SEND}
      - VALIDATOR_WEBHOOK_PRIVATE_KEY=${VALIDATOR_WEBHOOK_PRIVATE_KEY}
      - VALIDATOR_WEBHOOK_APP_NAME=${VALIDATOR_WEBHOOK_APP_NAME}
      - VALIDATOR_WEBHOOK_DECRYPT_SECRET=${VALIDATOR_WEBHOOK_DECRYPT_SECRET}
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    volumes:
      - ./messages:/app/messages
